import { getIconUrlByName } from "vscode-material-icons";

const ICONS_URL = "/icons";

type IconName = Parameters<typeof getIconUrlByName>[0];

const folderIcons = {
  admin: "folder-admin",
  android: "folder-android",
  angular: "folder-angular",
  animation: "folder-animation",
  ansible: "folder-ansible",
  api: "folder-api",
  apollo: "folder-apollo",
  app: "folder-app",
  archive: "folder-archive",
  audio: "folder-audio",
  aurelia: "folder-aurelia",
  aws: "folder-aws",
  "azure-pipelines": "folder-azure-pipelines",
  base: "folder-base",
  batch: "folder-batch",
  benchmark: "folder-benchmark",
  bower: "folder-bower",
  buildkite: "folder-buildkite",
  cart: "folder-cart",
  changesets: "folder-changesets",
  ci: "folder-ci",
  circleci: "folder-circleci",
  class: "folder-class",
  client: "folder-client",
  cloudflare: "folder-cloudflare",
  cluster: "folder-cluster",
  cobol: "folder-cobol",
  command: "folder-command",
  components: "folder-components",
  config: "folder-config",
  connection: "folder-connection",
  console: "folder-console",
  constant: "folder-constant",
  container: "folder-container",
  content: "folder-content",
  context: "folder-context",
  contract: "folder-contract",
  controller: "folder-controller",
  core: "folder-core",
  coverage: "folder-coverage",
  css: "folder-css",
  custom: "folder-custom",
  cypress: "folder-cypress",
  database: "folder-database",
  debug: "folder-debug",
  decorators: "folder-decorators",
  delta: "folder-delta",
  desktop: "folder-desktop",
  dist: "folder-dist",
  docker: "folder-docker",
  docs: "folder-docs",
  download: "folder-download",
  dump: "folder-dump",
  enum: "folder-enum",
  environment: "folder-environment",
  error: "folder-error",
  event: "folder-event",
  examples: "folder-examples",
  expo: "folder-expo",
  export: "folder-export",
  fastlane: "folder-fastlane",
  firebase: "folder-firebase",
  flow: "folder-flow",
  font: "folder-font",
  functions: "folder-functions",
  gamemaker: "folder-gamemaker",
  generator: "folder-generator",
  git: "folder-git",
  github: "folder-github",
  gitlab: "folder-gitlab",
  global: "folder-global",
  godot: "folder-godot",
  gradle: "folder-gradle",
  graphql: "folder-graphql",
  guard: "folder-guard",
  gulp: "folder-gulp",
  helper: "folder-helper",
  home: "folder-home",
  hook: "folder-hook",
  husky: "folder-husky",
  i18n: "folder-i18n",
  images: "folder-images",
  import: "folder-import",
  include: "folder-include",
  intellij: "folder-intellij",
  interface: "folder-interface",
  ios: "folder-ios",
  java: "folder-java",
  javascript: "folder-javascript",
  jinja: "folder-jinja",
  job: "folder-job",
  json: "folder-json",
  keys: "folder-keys",
  kubernetes: "folder-kubernetes",
  layout: "folder-layout",
  less: "folder-less",
  lib: "folder-lib",
  linux: "folder-linux",
  log: "folder-log",
  lottie: "folder-lottie",
  lua: "folder-lua",
  macos: "folder-macos",
  mail: "folder-mail",
  mappings: "folder-mappings",
  markdown: "folder-markdown",
  mercurial: "folder-mercurial",
  messages: "folder-messages",
  meta: "folder-meta",
  middleware: "folder-middleware",
  mjml: "folder-mjml",
  mobile: "folder-mobile",
  mock: "folder-mock",
  mojo: "folder-mojo",
  moon: "folder-moon",
  netlify: "folder-netlify",
  next: "folder-next",
  "ngrx-actions": "folder-ngrx-actions",
  "ngrx-effects": "folder-ngrx-effects",
  "ngrx-entities": "folder-ngrx-entities",
  "ngrx-reducer": "folder-ngrx-reducer",
  "ngrx-selectors": "folder-ngrx-selectors",
  "ngrx-state": "folder-ngrx-state",
  "ngrx-store": "folder-ngrx-store",
  node: "folder-node",
  nuxt: "folder-nuxt",
  other: "folder-other",
  packages: "folder-packages",
  pdf: "folder-pdf",
  pdm: "folder-pdm",
  php: "folder-php",
  phpmailer: "folder-phpmailer",
  pipe: "folder-pipe",
  plastic: "folder-plastic",
  plugin: "folder-plugin",
  prisma: "folder-prisma",
  private: "folder-private",
  project: "folder-project",
  proto: "folder-proto",
  public: "folder-public",
  python: "folder-python",
  quasar: "folder-quasar",
  queue: "folder-queue",
  "react-components": "folder-react-components",
  "redux-actions": "folder-redux-actions",
  "redux-reducer": "folder-redux-reducer",
  "redux-selector": "folder-redux-selector",
  "redux-store": "folder-redux-store",
  resolver: "folder-resolver",
  resource: "folder-resource",
  review: "folder-review",
  robot: "folder-robot",
  root: "folder-root",
  routes: "folder-routes",
  rules: "folder-rules",
  sass: "folder-sass",
  scala: "folder-scala",
  scripts: "folder-scripts",
  secure: "folder-secure",
  seeders: "folder-seeders",
  server: "folder-server",
  serverless: "folder-serverless",
  shader: "folder-shader",
  shared: "folder-shared",
  src: "folder-src",
  stack: "folder-stack",
  stencil: "folder-stencil",
  storybook: "folder-storybook",
  stylus: "folder-stylus",
  sublime: "folder-sublime",
  supabase: "folder-supabase",
  svelte: "folder-svelte",
  svg: "folder-svg",
  syntax: "folder-syntax",
  target: "folder-target",
  taskfile: "folder-taskfile",
  tasks: "folder-tasks",
  television: "folder-television",
  temp: "folder-temp",
  template: "folder-template",
  terraform: "folder-terraform",
  test: "folder-test",
  theme: "folder-theme",
  tools: "folder-tools",
  typescript: "folder-typescript",
  unity: "folder-unity",
  update: "folder-update",
  upload: "folder-upload",
  utils: "folder-utils",
  vercel: "folder-vercel",
  verdaccio: "folder-verdaccio",
  video: "folder-video",
  views: "folder-views",
  vm: "folder-vm",
  vscode: "folder-vscode",
  vue: "folder-vue",
  "vue-directives": "folder-vue-directives",
  vuepress: "folder-vuepress",
  "vuex-store": "folder-vuex-store",
  wakatime: "folder-wakatime",
  webpack: "folder-webpack",
  windows: "folder-windows",
  wordpress: "folder-wordpress",
  yarn: "folder-yarn",
} as const;

const folderAliases = {
  ".github": "folder-github",
  ".gitlab": "folder-gitlab",
  ".git": "folder-git",
  node_modules: "folder-node",
  "react-components": "folder-react-components",
  "redux-store": "folder-redux-store",
  "redux-actions": "folder-redux-actions",
  "redux-reducer": "folder-redux-reducer",
  "redux-selector": "folder-redux-selector",
  "ngrx-actions": "folder-ngrx-actions",
  "ngrx-effects": "folder-ngrx-effects",
  "ngrx-entities": "folder-ngrx-entities",
  "ngrx-reducer": "folder-ngrx-reducer",
  "ngrx-selectors": "folder-ngrx-selectors",
  "ngrx-state": "folder-ngrx-state",
  "ngrx-store": "folder-ngrx-store",
  "vue-directives": "folder-vue-directives",
  "vuex-store": "folder-vuex-store",
  "azure-pipelines": "folder-azure-pipelines",
  i18n: "folder-i18n",
  phpmailer: "folder-phpmailer",
} as const;

export function getFolderIcon(folderName: string): string {
  const normalized = folderName.trim().toLowerCase();

  // If the folder name is empty, use the normal folder.
  if (!normalized) {
    return getIconUrlByName("folder", ICONS_URL);
  }

  // Special names first.
  const alias =
    folderAliases[normalized as keyof typeof folderAliases];

  if (alias) {
    return getIconUrlByName(alias as IconName, ICONS_URL);
  }

  // Normal folder-name mapping.
  const iconName =
    folderIcons[normalized as keyof typeof folderIcons];

  if (iconName) {
    return getIconUrlByName(iconName as IconName, ICONS_URL);
  }

  // Unknown folder → normal folder icon.
  return getIconUrlByName("folder", ICONS_URL);
}