/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReposRouteImport } from './routes/_app/repos'
import { Route as AppPullsRouteImport } from './routes/_app/pulls'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppIssuesRouteImport } from './routes/_app/issues'
import { Route as UsernameRepoRouteRouteImport } from './routes/$username/$repo/route'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as UsernameRepoIndexRouteImport } from './routes/$username/$repo/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrgsNewRouteImport } from './routes/_app/orgs/new'
import { Route as UsernameRepoTagsRouteImport } from './routes/$username/$repo/tags'
import { Route as UsernameRepoSecurityRouteImport } from './routes/$username/$repo/security'
import { Route as UsernameRepoForksRouteImport } from './routes/$username/$repo/forks'
import { Route as UsernameRepoCommitsRouteImport } from './routes/$username/$repo/commits'
import { Route as UsernameRepoCodeRouteImport } from './routes/$username/$repo/code'
import { Route as UsernameRepoActionsRouteImport } from './routes/$username/$repo/actions'
import { Route as AppOrgsOrgRouteRouteImport } from './routes/_app/orgs/$org/route'
import { Route as UsernameRepoSettingsRouteRouteImport } from './routes/$username/$repo/settings/route'
import { Route as UsernameRepoIssuesRouteRouteImport } from './routes/$username/$repo/issues/route'
import { Route as UsernameRepoInsightRouteRouteImport } from './routes/$username/$repo/insight/route'
import { Route as UsernameRepoCompareRouteRouteImport } from './routes/$username/$repo/compare/route'
import { Route as AppOrgsOrgIndexRouteImport } from './routes/_app/orgs/$org/index'
import { Route as UsernameRepoPullsIndexRouteImport } from './routes/$username/$repo/pulls/index'
import { Route as UsernameRepoIssuesIndexRouteImport } from './routes/$username/$repo/issues/index'
import { Route as UsernameRepoInsightIndexRouteImport } from './routes/$username/$repo/insight/index'
import { Route as UsernameRepoCompareIndexRouteImport } from './routes/$username/$repo/compare/index'
import { Route as AppOrgsOrgTeamsRouteImport } from './routes/_app/orgs/$org/teams'
import { Route as AppOrgsOrgSettingsRouteImport } from './routes/_app/orgs/$org/settings'
import { Route as AppOrgsOrgRepositoriesRouteImport } from './routes/_app/orgs/$org/repositories'
import { Route as AppOrgsOrgPeopleRouteImport } from './routes/_app/orgs/$org/people'
import { Route as UsernameRepoTreeBranchRouteImport } from './routes/$username/$repo/tree/$branch'
import { Route as UsernameRepoTagTagNameRouteImport } from './routes/$username/$repo/tag/$tagName'
import { Route as UsernameRepoPullsPullRouteImport } from './routes/$username/$repo/pulls/$pull'
import { Route as UsernameRepoIssuesNewRouteImport } from './routes/$username/$repo/issues/new'
import { Route as UsernameRepoIssuesIssueRouteImport } from './routes/$username/$repo/issues/$issue'
import { Route as UsernameRepoInsightRecentCommitsRouteImport } from './routes/$username/$repo/insight/recent-commits'
import { Route as UsernameRepoInsightContributorsRouteImport } from './routes/$username/$repo/insight/contributors'
import { Route as UsernameRepoInsightCodeFrequencyRouteImport } from './routes/$username/$repo/insight/code-frequency'
import { Route as UsernameRepoCompareSplatRouteImport } from './routes/$username/$repo/compare/$'
import { Route as UsernameRepoCommitsHashRouteImport } from './routes/$username/$repo/commits.$hash'
import { Route as UsernameRepoBranchBranchNameRouteImport } from './routes/$username/$repo/branch/$branchName'
import { Route as UsernameRepoTreeBranchIndexRouteImport } from './routes/$username/$repo/tree/$branch/index'
import { Route as UsernameRepoTreeBranchSplatRouteImport } from './routes/$username/$repo/tree/$branch/$'
import { Route as UsernameRepoBlobBranchSplatRouteImport } from './routes/$username/$repo/blob/$branch/$'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRoute,
} as any)
const AppPullsRoute = AppPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const UsernameRepoRouteRoute = UsernameRepoRouteRouteImport.update({
  id: '/$username/$repo',
  path: '/$username/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const UsernameRepoIndexRoute = UsernameRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgsNewRoute = AppOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AppRoute,
} as any)
const UsernameRepoTagsRoute = UsernameRepoTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoSecurityRoute = UsernameRepoSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoForksRoute = UsernameRepoForksRouteImport.update({
  id: '/forks',
  path: '/forks',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoCommitsRoute = UsernameRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoCodeRoute = UsernameRepoCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoActionsRoute = UsernameRepoActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const AppOrgsOrgRouteRoute = AppOrgsOrgRouteRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => AppRoute,
} as any)
const UsernameRepoSettingsRouteRoute =
  UsernameRepoSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => UsernameRepoRouteRoute,
  } as any)
const UsernameRepoIssuesRouteRoute = UsernameRepoIssuesRouteRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoInsightRouteRoute =
  UsernameRepoInsightRouteRouteImport.update({
    id: '/insight',
    path: '/insight',
    getParentRoute: () => UsernameRepoRouteRoute,
  } as any)
const UsernameRepoCompareRouteRoute =
  UsernameRepoCompareRouteRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => UsernameRepoRouteRoute,
  } as any)
const AppOrgsOrgIndexRoute = AppOrgsOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsOrgRouteRoute,
} as any)
const UsernameRepoPullsIndexRoute = UsernameRepoPullsIndexRouteImport.update({
  id: '/pulls/',
  path: '/pulls/',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoIssuesIndexRoute = UsernameRepoIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRepoIssuesRouteRoute,
} as any)
const UsernameRepoInsightIndexRoute =
  UsernameRepoInsightIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UsernameRepoInsightRouteRoute,
  } as any)
const UsernameRepoCompareIndexRoute =
  UsernameRepoCompareIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UsernameRepoCompareRouteRoute,
  } as any)
const AppOrgsOrgTeamsRoute = AppOrgsOrgTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppOrgsOrgRouteRoute,
} as any)
const AppOrgsOrgSettingsRoute = AppOrgsOrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgsOrgRouteRoute,
} as any)
const AppOrgsOrgRepositoriesRoute = AppOrgsOrgRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppOrgsOrgRouteRoute,
} as any)
const AppOrgsOrgPeopleRoute = AppOrgsOrgPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppOrgsOrgRouteRoute,
} as any)
const UsernameRepoTreeBranchRoute = UsernameRepoTreeBranchRouteImport.update({
  id: '/tree/$branch',
  path: '/tree/$branch',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoTagTagNameRoute = UsernameRepoTagTagNameRouteImport.update({
  id: '/tag/$tagName',
  path: '/tag/$tagName',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoPullsPullRoute = UsernameRepoPullsPullRouteImport.update({
  id: '/pulls/$pull',
  path: '/pulls/$pull',
  getParentRoute: () => UsernameRepoRouteRoute,
} as any)
const UsernameRepoIssuesNewRoute = UsernameRepoIssuesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsernameRepoIssuesRouteRoute,
} as any)
const UsernameRepoIssuesIssueRoute = UsernameRepoIssuesIssueRouteImport.update({
  id: '/$issue',
  path: '/$issue',
  getParentRoute: () => UsernameRepoIssuesRouteRoute,
} as any)
const UsernameRepoInsightRecentCommitsRoute =
  UsernameRepoInsightRecentCommitsRouteImport.update({
    id: '/recent-commits',
    path: '/recent-commits',
    getParentRoute: () => UsernameRepoInsightRouteRoute,
  } as any)
const UsernameRepoInsightContributorsRoute =
  UsernameRepoInsightContributorsRouteImport.update({
    id: '/contributors',
    path: '/contributors',
    getParentRoute: () => UsernameRepoInsightRouteRoute,
  } as any)
const UsernameRepoInsightCodeFrequencyRoute =
  UsernameRepoInsightCodeFrequencyRouteImport.update({
    id: '/code-frequency',
    path: '/code-frequency',
    getParentRoute: () => UsernameRepoInsightRouteRoute,
  } as any)
const UsernameRepoCompareSplatRoute =
  UsernameRepoCompareSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => UsernameRepoCompareRouteRoute,
  } as any)
const UsernameRepoCommitsHashRoute = UsernameRepoCommitsHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => UsernameRepoCommitsRoute,
} as any)
const UsernameRepoBranchBranchNameRoute =
  UsernameRepoBranchBranchNameRouteImport.update({
    id: '/branch/$branchName',
    path: '/branch/$branchName',
    getParentRoute: () => UsernameRepoRouteRoute,
  } as any)
const UsernameRepoTreeBranchIndexRoute =
  UsernameRepoTreeBranchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UsernameRepoTreeBranchRoute,
  } as any)
const UsernameRepoTreeBranchSplatRoute =
  UsernameRepoTreeBranchSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => UsernameRepoTreeBranchRoute,
  } as any)
const UsernameRepoBlobBranchSplatRoute =
  UsernameRepoBlobBranchSplatRouteImport.update({
    id: '/blob/$branch/$',
    path: '/blob/$branch/$',
    getParentRoute: () => UsernameRepoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$username/$repo': typeof UsernameRepoRouteRouteWithChildren
  '/issues': typeof AppIssuesRoute
  '/new': typeof AppNewRoute
  '/pulls': typeof AppPullsRoute
  '/repos': typeof AppReposRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/$username/': typeof UsernameIndexRoute
  '/$username/$repo/compare': typeof UsernameRepoCompareRouteRouteWithChildren
  '/$username/$repo/insight': typeof UsernameRepoInsightRouteRouteWithChildren
  '/$username/$repo/issues': typeof UsernameRepoIssuesRouteRouteWithChildren
  '/$username/$repo/settings': typeof UsernameRepoSettingsRouteRoute
  '/orgs/$org': typeof AppOrgsOrgRouteRouteWithChildren
  '/$username/$repo/actions': typeof UsernameRepoActionsRoute
  '/$username/$repo/code': typeof UsernameRepoCodeRoute
  '/$username/$repo/commits': typeof UsernameRepoCommitsRouteWithChildren
  '/$username/$repo/forks': typeof UsernameRepoForksRoute
  '/$username/$repo/security': typeof UsernameRepoSecurityRoute
  '/$username/$repo/tags': typeof UsernameRepoTagsRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$username/$repo/': typeof UsernameRepoIndexRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/$username/$repo/branch/$branchName': typeof UsernameRepoBranchBranchNameRoute
  '/$username/$repo/commits/$hash': typeof UsernameRepoCommitsHashRoute
  '/$username/$repo/compare/$': typeof UsernameRepoCompareSplatRoute
  '/$username/$repo/insight/code-frequency': typeof UsernameRepoInsightCodeFrequencyRoute
  '/$username/$repo/insight/contributors': typeof UsernameRepoInsightContributorsRoute
  '/$username/$repo/insight/recent-commits': typeof UsernameRepoInsightRecentCommitsRoute
  '/$username/$repo/issues/$issue': typeof UsernameRepoIssuesIssueRoute
  '/$username/$repo/issues/new': typeof UsernameRepoIssuesNewRoute
  '/$username/$repo/pulls/$pull': typeof UsernameRepoPullsPullRoute
  '/$username/$repo/tag/$tagName': typeof UsernameRepoTagTagNameRoute
  '/$username/$repo/tree/$branch': typeof UsernameRepoTreeBranchRouteWithChildren
  '/orgs/$org/people': typeof AppOrgsOrgPeopleRoute
  '/orgs/$org/repositories': typeof AppOrgsOrgRepositoriesRoute
  '/orgs/$org/settings': typeof AppOrgsOrgSettingsRoute
  '/orgs/$org/teams': typeof AppOrgsOrgTeamsRoute
  '/$username/$repo/compare/': typeof UsernameRepoCompareIndexRoute
  '/$username/$repo/insight/': typeof UsernameRepoInsightIndexRoute
  '/$username/$repo/issues/': typeof UsernameRepoIssuesIndexRoute
  '/$username/$repo/pulls/': typeof UsernameRepoPullsIndexRoute
  '/orgs/$org/': typeof AppOrgsOrgIndexRoute
  '/$username/$repo/blob/$branch/$': typeof UsernameRepoBlobBranchSplatRoute
  '/$username/$repo/tree/$branch/$': typeof UsernameRepoTreeBranchSplatRoute
  '/$username/$repo/tree/$branch/': typeof UsernameRepoTreeBranchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/issues': typeof AppIssuesRoute
  '/new': typeof AppNewRoute
  '/pulls': typeof AppPullsRoute
  '/repos': typeof AppReposRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/$username': typeof UsernameIndexRoute
  '/$username/$repo/settings': typeof UsernameRepoSettingsRouteRoute
  '/$username/$repo/actions': typeof UsernameRepoActionsRoute
  '/$username/$repo/code': typeof UsernameRepoCodeRoute
  '/$username/$repo/commits': typeof UsernameRepoCommitsRouteWithChildren
  '/$username/$repo/forks': typeof UsernameRepoForksRoute
  '/$username/$repo/security': typeof UsernameRepoSecurityRoute
  '/$username/$repo/tags': typeof UsernameRepoTagsRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$username/$repo': typeof UsernameRepoIndexRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/$username/$repo/branch/$branchName': typeof UsernameRepoBranchBranchNameRoute
  '/$username/$repo/commits/$hash': typeof UsernameRepoCommitsHashRoute
  '/$username/$repo/compare/$': typeof UsernameRepoCompareSplatRoute
  '/$username/$repo/insight/code-frequency': typeof UsernameRepoInsightCodeFrequencyRoute
  '/$username/$repo/insight/contributors': typeof UsernameRepoInsightContributorsRoute
  '/$username/$repo/insight/recent-commits': typeof UsernameRepoInsightRecentCommitsRoute
  '/$username/$repo/issues/$issue': typeof UsernameRepoIssuesIssueRoute
  '/$username/$repo/issues/new': typeof UsernameRepoIssuesNewRoute
  '/$username/$repo/pulls/$pull': typeof UsernameRepoPullsPullRoute
  '/$username/$repo/tag/$tagName': typeof UsernameRepoTagTagNameRoute
  '/orgs/$org/people': typeof AppOrgsOrgPeopleRoute
  '/orgs/$org/repositories': typeof AppOrgsOrgRepositoriesRoute
  '/orgs/$org/settings': typeof AppOrgsOrgSettingsRoute
  '/orgs/$org/teams': typeof AppOrgsOrgTeamsRoute
  '/$username/$repo/compare': typeof UsernameRepoCompareIndexRoute
  '/$username/$repo/insight': typeof UsernameRepoInsightIndexRoute
  '/$username/$repo/issues': typeof UsernameRepoIssuesIndexRoute
  '/$username/$repo/pulls': typeof UsernameRepoPullsIndexRoute
  '/orgs/$org': typeof AppOrgsOrgIndexRoute
  '/$username/$repo/blob/$branch/$': typeof UsernameRepoBlobBranchSplatRoute
  '/$username/$repo/tree/$branch/$': typeof UsernameRepoTreeBranchSplatRoute
  '/$username/$repo/tree/$branch': typeof UsernameRepoTreeBranchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/$username/$repo': typeof UsernameRepoRouteRouteWithChildren
  '/_app/issues': typeof AppIssuesRoute
  '/_app/new': typeof AppNewRoute
  '/_app/pulls': typeof AppPullsRoute
  '/_app/repos': typeof AppReposRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/$username/': typeof UsernameIndexRoute
  '/$username/$repo/compare': typeof UsernameRepoCompareRouteRouteWithChildren
  '/$username/$repo/insight': typeof UsernameRepoInsightRouteRouteWithChildren
  '/$username/$repo/issues': typeof UsernameRepoIssuesRouteRouteWithChildren
  '/$username/$repo/settings': typeof UsernameRepoSettingsRouteRoute
  '/_app/orgs/$org': typeof AppOrgsOrgRouteRouteWithChildren
  '/$username/$repo/actions': typeof UsernameRepoActionsRoute
  '/$username/$repo/code': typeof UsernameRepoCodeRoute
  '/$username/$repo/commits': typeof UsernameRepoCommitsRouteWithChildren
  '/$username/$repo/forks': typeof UsernameRepoForksRoute
  '/$username/$repo/security': typeof UsernameRepoSecurityRoute
  '/$username/$repo/tags': typeof UsernameRepoTagsRoute
  '/_app/orgs/new': typeof AppOrgsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$username/$repo/': typeof UsernameRepoIndexRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/$username/$repo/branch/$branchName': typeof UsernameRepoBranchBranchNameRoute
  '/$username/$repo/commits/$hash': typeof UsernameRepoCommitsHashRoute
  '/$username/$repo/compare/$': typeof UsernameRepoCompareSplatRoute
  '/$username/$repo/insight/code-frequency': typeof UsernameRepoInsightCodeFrequencyRoute
  '/$username/$repo/insight/contributors': typeof UsernameRepoInsightContributorsRoute
  '/$username/$repo/insight/recent-commits': typeof UsernameRepoInsightRecentCommitsRoute
  '/$username/$repo/issues/$issue': typeof UsernameRepoIssuesIssueRoute
  '/$username/$repo/issues/new': typeof UsernameRepoIssuesNewRoute
  '/$username/$repo/pulls/$pull': typeof UsernameRepoPullsPullRoute
  '/$username/$repo/tag/$tagName': typeof UsernameRepoTagTagNameRoute
  '/$username/$repo/tree/$branch': typeof UsernameRepoTreeBranchRouteWithChildren
  '/_app/orgs/$org/people': typeof AppOrgsOrgPeopleRoute
  '/_app/orgs/$org/repositories': typeof AppOrgsOrgRepositoriesRoute
  '/_app/orgs/$org/settings': typeof AppOrgsOrgSettingsRoute
  '/_app/orgs/$org/teams': typeof AppOrgsOrgTeamsRoute
  '/$username/$repo/compare/': typeof UsernameRepoCompareIndexRoute
  '/$username/$repo/insight/': typeof UsernameRepoInsightIndexRoute
  '/$username/$repo/issues/': typeof UsernameRepoIssuesIndexRoute
  '/$username/$repo/pulls/': typeof UsernameRepoPullsIndexRoute
  '/_app/orgs/$org/': typeof AppOrgsOrgIndexRoute
  '/$username/$repo/blob/$branch/$': typeof UsernameRepoBlobBranchSplatRoute
  '/$username/$repo/tree/$branch/$': typeof UsernameRepoTreeBranchSplatRoute
  '/$username/$repo/tree/$branch/': typeof UsernameRepoTreeBranchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$username/$repo'
    | '/issues'
    | '/new'
    | '/pulls'
    | '/repos'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/$username/'
    | '/$username/$repo/compare'
    | '/$username/$repo/insight'
    | '/$username/$repo/issues'
    | '/$username/$repo/settings'
    | '/orgs/$org'
    | '/$username/$repo/actions'
    | '/$username/$repo/code'
    | '/$username/$repo/commits'
    | '/$username/$repo/forks'
    | '/$username/$repo/security'
    | '/$username/$repo/tags'
    | '/orgs/new'
    | '/api/auth/$'
    | '/$username/$repo/'
    | '/orgs/'
    | '/$username/$repo/branch/$branchName'
    | '/$username/$repo/commits/$hash'
    | '/$username/$repo/compare/$'
    | '/$username/$repo/insight/code-frequency'
    | '/$username/$repo/insight/contributors'
    | '/$username/$repo/insight/recent-commits'
    | '/$username/$repo/issues/$issue'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/pulls/$pull'
    | '/$username/$repo/tag/$tagName'
    | '/$username/$repo/tree/$branch'
    | '/orgs/$org/people'
    | '/orgs/$org/repositories'
    | '/orgs/$org/settings'
    | '/orgs/$org/teams'
    | '/$username/$repo/compare/'
    | '/$username/$repo/insight/'
    | '/$username/$repo/issues/'
    | '/$username/$repo/pulls/'
    | '/orgs/$org/'
    | '/$username/$repo/blob/$branch/$'
    | '/$username/$repo/tree/$branch/$'
    | '/$username/$repo/tree/$branch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/issues'
    | '/new'
    | '/pulls'
    | '/repos'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/$username'
    | '/$username/$repo/settings'
    | '/$username/$repo/actions'
    | '/$username/$repo/code'
    | '/$username/$repo/commits'
    | '/$username/$repo/forks'
    | '/$username/$repo/security'
    | '/$username/$repo/tags'
    | '/orgs/new'
    | '/api/auth/$'
    | '/$username/$repo'
    | '/orgs'
    | '/$username/$repo/branch/$branchName'
    | '/$username/$repo/commits/$hash'
    | '/$username/$repo/compare/$'
    | '/$username/$repo/insight/code-frequency'
    | '/$username/$repo/insight/contributors'
    | '/$username/$repo/insight/recent-commits'
    | '/$username/$repo/issues/$issue'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/pulls/$pull'
    | '/$username/$repo/tag/$tagName'
    | '/orgs/$org/people'
    | '/orgs/$org/repositories'
    | '/orgs/$org/settings'
    | '/orgs/$org/teams'
    | '/$username/$repo/compare'
    | '/$username/$repo/insight'
    | '/$username/$repo/issues'
    | '/$username/$repo/pulls'
    | '/orgs/$org'
    | '/$username/$repo/blob/$branch/$'
    | '/$username/$repo/tree/$branch/$'
    | '/$username/$repo/tree/$branch'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_auth'
    | '/$username/$repo'
    | '/_app/issues'
    | '/_app/new'
    | '/_app/pulls'
    | '/_app/repos'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/$username/'
    | '/$username/$repo/compare'
    | '/$username/$repo/insight'
    | '/$username/$repo/issues'
    | '/$username/$repo/settings'
    | '/_app/orgs/$org'
    | '/$username/$repo/actions'
    | '/$username/$repo/code'
    | '/$username/$repo/commits'
    | '/$username/$repo/forks'
    | '/$username/$repo/security'
    | '/$username/$repo/tags'
    | '/_app/orgs/new'
    | '/api/auth/$'
    | '/$username/$repo/'
    | '/_app/orgs/'
    | '/$username/$repo/branch/$branchName'
    | '/$username/$repo/commits/$hash'
    | '/$username/$repo/compare/$'
    | '/$username/$repo/insight/code-frequency'
    | '/$username/$repo/insight/contributors'
    | '/$username/$repo/insight/recent-commits'
    | '/$username/$repo/issues/$issue'
    | '/$username/$repo/issues/new'
    | '/$username/$repo/pulls/$pull'
    | '/$username/$repo/tag/$tagName'
    | '/$username/$repo/tree/$branch'
    | '/_app/orgs/$org/people'
    | '/_app/orgs/$org/repositories'
    | '/_app/orgs/$org/settings'
    | '/_app/orgs/$org/teams'
    | '/$username/$repo/compare/'
    | '/$username/$repo/insight/'
    | '/$username/$repo/issues/'
    | '/$username/$repo/pulls/'
    | '/_app/orgs/$org/'
    | '/$username/$repo/blob/$branch/$'
    | '/$username/$repo/tree/$branch/$'
    | '/$username/$repo/tree/$branch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UsernameRepoRouteRoute: typeof UsernameRepoRouteRouteWithChildren
  UsernameIndexRoute: typeof UsernameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos': {
      id: '/_app/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pulls': {
      id: '/_app/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof AppPullsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/$username/$repo': {
      id: '/$username/$repo'
      path: '/$username/$repo'
      fullPath: '/$username/$repo'
      preLoaderRoute: typeof UsernameRepoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/$username/$repo/': {
      id: '/$username/$repo/'
      path: '/'
      fullPath: '/$username/$repo/'
      preLoaderRoute: typeof UsernameRepoIndexRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orgs/new': {
      id: '/_app/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AppOrgsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/$username/$repo/tags': {
      id: '/$username/$repo/tags'
      path: '/tags'
      fullPath: '/$username/$repo/tags'
      preLoaderRoute: typeof UsernameRepoTagsRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/security': {
      id: '/$username/$repo/security'
      path: '/security'
      fullPath: '/$username/$repo/security'
      preLoaderRoute: typeof UsernameRepoSecurityRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/forks': {
      id: '/$username/$repo/forks'
      path: '/forks'
      fullPath: '/$username/$repo/forks'
      preLoaderRoute: typeof UsernameRepoForksRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/commits': {
      id: '/$username/$repo/commits'
      path: '/commits'
      fullPath: '/$username/$repo/commits'
      preLoaderRoute: typeof UsernameRepoCommitsRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/code': {
      id: '/$username/$repo/code'
      path: '/code'
      fullPath: '/$username/$repo/code'
      preLoaderRoute: typeof UsernameRepoCodeRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/actions': {
      id: '/$username/$repo/actions'
      path: '/actions'
      fullPath: '/$username/$repo/actions'
      preLoaderRoute: typeof UsernameRepoActionsRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/_app/orgs/$org': {
      id: '/_app/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/orgs/$org'
      preLoaderRoute: typeof AppOrgsOrgRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/$username/$repo/settings': {
      id: '/$username/$repo/settings'
      path: '/settings'
      fullPath: '/$username/$repo/settings'
      preLoaderRoute: typeof UsernameRepoSettingsRouteRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/issues': {
      id: '/$username/$repo/issues'
      path: '/issues'
      fullPath: '/$username/$repo/issues'
      preLoaderRoute: typeof UsernameRepoIssuesRouteRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/insight': {
      id: '/$username/$repo/insight'
      path: '/insight'
      fullPath: '/$username/$repo/insight'
      preLoaderRoute: typeof UsernameRepoInsightRouteRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/compare': {
      id: '/$username/$repo/compare'
      path: '/compare'
      fullPath: '/$username/$repo/compare'
      preLoaderRoute: typeof UsernameRepoCompareRouteRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/_app/orgs/$org/': {
      id: '/_app/orgs/$org/'
      path: '/'
      fullPath: '/orgs/$org/'
      preLoaderRoute: typeof AppOrgsOrgIndexRouteImport
      parentRoute: typeof AppOrgsOrgRouteRoute
    }
    '/$username/$repo/pulls/': {
      id: '/$username/$repo/pulls/'
      path: '/pulls'
      fullPath: '/$username/$repo/pulls/'
      preLoaderRoute: typeof UsernameRepoPullsIndexRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/issues/': {
      id: '/$username/$repo/issues/'
      path: '/'
      fullPath: '/$username/$repo/issues/'
      preLoaderRoute: typeof UsernameRepoIssuesIndexRouteImport
      parentRoute: typeof UsernameRepoIssuesRouteRoute
    }
    '/$username/$repo/insight/': {
      id: '/$username/$repo/insight/'
      path: '/'
      fullPath: '/$username/$repo/insight/'
      preLoaderRoute: typeof UsernameRepoInsightIndexRouteImport
      parentRoute: typeof UsernameRepoInsightRouteRoute
    }
    '/$username/$repo/compare/': {
      id: '/$username/$repo/compare/'
      path: '/'
      fullPath: '/$username/$repo/compare/'
      preLoaderRoute: typeof UsernameRepoCompareIndexRouteImport
      parentRoute: typeof UsernameRepoCompareRouteRoute
    }
    '/_app/orgs/$org/teams': {
      id: '/_app/orgs/$org/teams'
      path: '/teams'
      fullPath: '/orgs/$org/teams'
      preLoaderRoute: typeof AppOrgsOrgTeamsRouteImport
      parentRoute: typeof AppOrgsOrgRouteRoute
    }
    '/_app/orgs/$org/settings': {
      id: '/_app/orgs/$org/settings'
      path: '/settings'
      fullPath: '/orgs/$org/settings'
      preLoaderRoute: typeof AppOrgsOrgSettingsRouteImport
      parentRoute: typeof AppOrgsOrgRouteRoute
    }
    '/_app/orgs/$org/repositories': {
      id: '/_app/orgs/$org/repositories'
      path: '/repositories'
      fullPath: '/orgs/$org/repositories'
      preLoaderRoute: typeof AppOrgsOrgRepositoriesRouteImport
      parentRoute: typeof AppOrgsOrgRouteRoute
    }
    '/_app/orgs/$org/people': {
      id: '/_app/orgs/$org/people'
      path: '/people'
      fullPath: '/orgs/$org/people'
      preLoaderRoute: typeof AppOrgsOrgPeopleRouteImport
      parentRoute: typeof AppOrgsOrgRouteRoute
    }
    '/$username/$repo/tree/$branch': {
      id: '/$username/$repo/tree/$branch'
      path: '/tree/$branch'
      fullPath: '/$username/$repo/tree/$branch'
      preLoaderRoute: typeof UsernameRepoTreeBranchRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/tag/$tagName': {
      id: '/$username/$repo/tag/$tagName'
      path: '/tag/$tagName'
      fullPath: '/$username/$repo/tag/$tagName'
      preLoaderRoute: typeof UsernameRepoTagTagNameRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/pulls/$pull': {
      id: '/$username/$repo/pulls/$pull'
      path: '/pulls/$pull'
      fullPath: '/$username/$repo/pulls/$pull'
      preLoaderRoute: typeof UsernameRepoPullsPullRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/issues/new': {
      id: '/$username/$repo/issues/new'
      path: '/new'
      fullPath: '/$username/$repo/issues/new'
      preLoaderRoute: typeof UsernameRepoIssuesNewRouteImport
      parentRoute: typeof UsernameRepoIssuesRouteRoute
    }
    '/$username/$repo/issues/$issue': {
      id: '/$username/$repo/issues/$issue'
      path: '/$issue'
      fullPath: '/$username/$repo/issues/$issue'
      preLoaderRoute: typeof UsernameRepoIssuesIssueRouteImport
      parentRoute: typeof UsernameRepoIssuesRouteRoute
    }
    '/$username/$repo/insight/recent-commits': {
      id: '/$username/$repo/insight/recent-commits'
      path: '/recent-commits'
      fullPath: '/$username/$repo/insight/recent-commits'
      preLoaderRoute: typeof UsernameRepoInsightRecentCommitsRouteImport
      parentRoute: typeof UsernameRepoInsightRouteRoute
    }
    '/$username/$repo/insight/contributors': {
      id: '/$username/$repo/insight/contributors'
      path: '/contributors'
      fullPath: '/$username/$repo/insight/contributors'
      preLoaderRoute: typeof UsernameRepoInsightContributorsRouteImport
      parentRoute: typeof UsernameRepoInsightRouteRoute
    }
    '/$username/$repo/insight/code-frequency': {
      id: '/$username/$repo/insight/code-frequency'
      path: '/code-frequency'
      fullPath: '/$username/$repo/insight/code-frequency'
      preLoaderRoute: typeof UsernameRepoInsightCodeFrequencyRouteImport
      parentRoute: typeof UsernameRepoInsightRouteRoute
    }
    '/$username/$repo/compare/$': {
      id: '/$username/$repo/compare/$'
      path: '/$'
      fullPath: '/$username/$repo/compare/$'
      preLoaderRoute: typeof UsernameRepoCompareSplatRouteImport
      parentRoute: typeof UsernameRepoCompareRouteRoute
    }
    '/$username/$repo/commits/$hash': {
      id: '/$username/$repo/commits/$hash'
      path: '/$hash'
      fullPath: '/$username/$repo/commits/$hash'
      preLoaderRoute: typeof UsernameRepoCommitsHashRouteImport
      parentRoute: typeof UsernameRepoCommitsRoute
    }
    '/$username/$repo/branch/$branchName': {
      id: '/$username/$repo/branch/$branchName'
      path: '/branch/$branchName'
      fullPath: '/$username/$repo/branch/$branchName'
      preLoaderRoute: typeof UsernameRepoBranchBranchNameRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
    '/$username/$repo/tree/$branch/': {
      id: '/$username/$repo/tree/$branch/'
      path: '/'
      fullPath: '/$username/$repo/tree/$branch/'
      preLoaderRoute: typeof UsernameRepoTreeBranchIndexRouteImport
      parentRoute: typeof UsernameRepoTreeBranchRoute
    }
    '/$username/$repo/tree/$branch/$': {
      id: '/$username/$repo/tree/$branch/$'
      path: '/$'
      fullPath: '/$username/$repo/tree/$branch/$'
      preLoaderRoute: typeof UsernameRepoTreeBranchSplatRouteImport
      parentRoute: typeof UsernameRepoTreeBranchRoute
    }
    '/$username/$repo/blob/$branch/$': {
      id: '/$username/$repo/blob/$branch/$'
      path: '/blob/$branch/$'
      fullPath: '/$username/$repo/blob/$branch/$'
      preLoaderRoute: typeof UsernameRepoBlobBranchSplatRouteImport
      parentRoute: typeof UsernameRepoRouteRoute
    }
  }
}

interface AppOrgsOrgRouteRouteChildren {
  AppOrgsOrgPeopleRoute: typeof AppOrgsOrgPeopleRoute
  AppOrgsOrgRepositoriesRoute: typeof AppOrgsOrgRepositoriesRoute
  AppOrgsOrgSettingsRoute: typeof AppOrgsOrgSettingsRoute
  AppOrgsOrgTeamsRoute: typeof AppOrgsOrgTeamsRoute
  AppOrgsOrgIndexRoute: typeof AppOrgsOrgIndexRoute
}

const AppOrgsOrgRouteRouteChildren: AppOrgsOrgRouteRouteChildren = {
  AppOrgsOrgPeopleRoute: AppOrgsOrgPeopleRoute,
  AppOrgsOrgRepositoriesRoute: AppOrgsOrgRepositoriesRoute,
  AppOrgsOrgSettingsRoute: AppOrgsOrgSettingsRoute,
  AppOrgsOrgTeamsRoute: AppOrgsOrgTeamsRoute,
  AppOrgsOrgIndexRoute: AppOrgsOrgIndexRoute,
}

const AppOrgsOrgRouteRouteWithChildren = AppOrgsOrgRouteRoute._addFileChildren(
  AppOrgsOrgRouteRouteChildren,
)

interface AppRouteChildren {
  AppIssuesRoute: typeof AppIssuesRoute
  AppNewRoute: typeof AppNewRoute
  AppPullsRoute: typeof AppPullsRoute
  AppReposRoute: typeof AppReposRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOrgsOrgRouteRoute: typeof AppOrgsOrgRouteRouteWithChildren
  AppOrgsNewRoute: typeof AppOrgsNewRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIssuesRoute: AppIssuesRoute,
  AppNewRoute: AppNewRoute,
  AppPullsRoute: AppPullsRoute,
  AppReposRoute: AppReposRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOrgsOrgRouteRoute: AppOrgsOrgRouteRouteWithChildren,
  AppOrgsNewRoute: AppOrgsNewRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UsernameRepoCompareRouteRouteChildren {
  UsernameRepoCompareSplatRoute: typeof UsernameRepoCompareSplatRoute
  UsernameRepoCompareIndexRoute: typeof UsernameRepoCompareIndexRoute
}

const UsernameRepoCompareRouteRouteChildren: UsernameRepoCompareRouteRouteChildren =
  {
    UsernameRepoCompareSplatRoute: UsernameRepoCompareSplatRoute,
    UsernameRepoCompareIndexRoute: UsernameRepoCompareIndexRoute,
  }

const UsernameRepoCompareRouteRouteWithChildren =
  UsernameRepoCompareRouteRoute._addFileChildren(
    UsernameRepoCompareRouteRouteChildren,
  )

interface UsernameRepoInsightRouteRouteChildren {
  UsernameRepoInsightCodeFrequencyRoute: typeof UsernameRepoInsightCodeFrequencyRoute
  UsernameRepoInsightContributorsRoute: typeof UsernameRepoInsightContributorsRoute
  UsernameRepoInsightRecentCommitsRoute: typeof UsernameRepoInsightRecentCommitsRoute
  UsernameRepoInsightIndexRoute: typeof UsernameRepoInsightIndexRoute
}

const UsernameRepoInsightRouteRouteChildren: UsernameRepoInsightRouteRouteChildren =
  {
    UsernameRepoInsightCodeFrequencyRoute:
      UsernameRepoInsightCodeFrequencyRoute,
    UsernameRepoInsightContributorsRoute: UsernameRepoInsightContributorsRoute,
    UsernameRepoInsightRecentCommitsRoute:
      UsernameRepoInsightRecentCommitsRoute,
    UsernameRepoInsightIndexRoute: UsernameRepoInsightIndexRoute,
  }

const UsernameRepoInsightRouteRouteWithChildren =
  UsernameRepoInsightRouteRoute._addFileChildren(
    UsernameRepoInsightRouteRouteChildren,
  )

interface UsernameRepoIssuesRouteRouteChildren {
  UsernameRepoIssuesIssueRoute: typeof UsernameRepoIssuesIssueRoute
  UsernameRepoIssuesNewRoute: typeof UsernameRepoIssuesNewRoute
  UsernameRepoIssuesIndexRoute: typeof UsernameRepoIssuesIndexRoute
}

const UsernameRepoIssuesRouteRouteChildren: UsernameRepoIssuesRouteRouteChildren =
  {
    UsernameRepoIssuesIssueRoute: UsernameRepoIssuesIssueRoute,
    UsernameRepoIssuesNewRoute: UsernameRepoIssuesNewRoute,
    UsernameRepoIssuesIndexRoute: UsernameRepoIssuesIndexRoute,
  }

const UsernameRepoIssuesRouteRouteWithChildren =
  UsernameRepoIssuesRouteRoute._addFileChildren(
    UsernameRepoIssuesRouteRouteChildren,
  )

interface UsernameRepoCommitsRouteChildren {
  UsernameRepoCommitsHashRoute: typeof UsernameRepoCommitsHashRoute
}

const UsernameRepoCommitsRouteChildren: UsernameRepoCommitsRouteChildren = {
  UsernameRepoCommitsHashRoute: UsernameRepoCommitsHashRoute,
}

const UsernameRepoCommitsRouteWithChildren =
  UsernameRepoCommitsRoute._addFileChildren(UsernameRepoCommitsRouteChildren)

interface UsernameRepoTreeBranchRouteChildren {
  UsernameRepoTreeBranchSplatRoute: typeof UsernameRepoTreeBranchSplatRoute
  UsernameRepoTreeBranchIndexRoute: typeof UsernameRepoTreeBranchIndexRoute
}

const UsernameRepoTreeBranchRouteChildren: UsernameRepoTreeBranchRouteChildren =
  {
    UsernameRepoTreeBranchSplatRoute: UsernameRepoTreeBranchSplatRoute,
    UsernameRepoTreeBranchIndexRoute: UsernameRepoTreeBranchIndexRoute,
  }

const UsernameRepoTreeBranchRouteWithChildren =
  UsernameRepoTreeBranchRoute._addFileChildren(
    UsernameRepoTreeBranchRouteChildren,
  )

interface UsernameRepoRouteRouteChildren {
  UsernameRepoCompareRouteRoute: typeof UsernameRepoCompareRouteRouteWithChildren
  UsernameRepoInsightRouteRoute: typeof UsernameRepoInsightRouteRouteWithChildren
  UsernameRepoIssuesRouteRoute: typeof UsernameRepoIssuesRouteRouteWithChildren
  UsernameRepoSettingsRouteRoute: typeof UsernameRepoSettingsRouteRoute
  UsernameRepoActionsRoute: typeof UsernameRepoActionsRoute
  UsernameRepoCodeRoute: typeof UsernameRepoCodeRoute
  UsernameRepoCommitsRoute: typeof UsernameRepoCommitsRouteWithChildren
  UsernameRepoForksRoute: typeof UsernameRepoForksRoute
  UsernameRepoSecurityRoute: typeof UsernameRepoSecurityRoute
  UsernameRepoTagsRoute: typeof UsernameRepoTagsRoute
  UsernameRepoIndexRoute: typeof UsernameRepoIndexRoute
  UsernameRepoBranchBranchNameRoute: typeof UsernameRepoBranchBranchNameRoute
  UsernameRepoPullsPullRoute: typeof UsernameRepoPullsPullRoute
  UsernameRepoTagTagNameRoute: typeof UsernameRepoTagTagNameRoute
  UsernameRepoTreeBranchRoute: typeof UsernameRepoTreeBranchRouteWithChildren
  UsernameRepoPullsIndexRoute: typeof UsernameRepoPullsIndexRoute
  UsernameRepoBlobBranchSplatRoute: typeof UsernameRepoBlobBranchSplatRoute
}

const UsernameRepoRouteRouteChildren: UsernameRepoRouteRouteChildren = {
  UsernameRepoCompareRouteRoute: UsernameRepoCompareRouteRouteWithChildren,
  UsernameRepoInsightRouteRoute: UsernameRepoInsightRouteRouteWithChildren,
  UsernameRepoIssuesRouteRoute: UsernameRepoIssuesRouteRouteWithChildren,
  UsernameRepoSettingsRouteRoute: UsernameRepoSettingsRouteRoute,
  UsernameRepoActionsRoute: UsernameRepoActionsRoute,
  UsernameRepoCodeRoute: UsernameRepoCodeRoute,
  UsernameRepoCommitsRoute: UsernameRepoCommitsRouteWithChildren,
  UsernameRepoForksRoute: UsernameRepoForksRoute,
  UsernameRepoSecurityRoute: UsernameRepoSecurityRoute,
  UsernameRepoTagsRoute: UsernameRepoTagsRoute,
  UsernameRepoIndexRoute: UsernameRepoIndexRoute,
  UsernameRepoBranchBranchNameRoute: UsernameRepoBranchBranchNameRoute,
  UsernameRepoPullsPullRoute: UsernameRepoPullsPullRoute,
  UsernameRepoTagTagNameRoute: UsernameRepoTagTagNameRoute,
  UsernameRepoTreeBranchRoute: UsernameRepoTreeBranchRouteWithChildren,
  UsernameRepoPullsIndexRoute: UsernameRepoPullsIndexRoute,
  UsernameRepoBlobBranchSplatRoute: UsernameRepoBlobBranchSplatRoute,
}

const UsernameRepoRouteRouteWithChildren =
  UsernameRepoRouteRoute._addFileChildren(UsernameRepoRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UsernameRepoRouteRoute: UsernameRepoRouteRouteWithChildren,
  UsernameIndexRoute: UsernameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
