env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  VALIDATE_ALL_CODEBASE: false
  DEFAULT_BRANCH: main

  VALIDATE_GO: true
  VALIDATE_TYPESCRIPT_ES: true
  VALIDATE_JAVASCRIPT_ES: true
  VALIDATE_JSON: true
  VALIDATE_YAML: true
  VALIDATE_MARKDOWN: true
  VALIDATE_DOCKERFILE: true
  VALIDATE_BASH: true